CREATE TABLE DELICACY
(DELICACY_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, DELICACY_NAME varchar(255) NOT NULL, DELICACY_STORY varchar(255) NOT NULL, DELICACY_HIGHLIGHT varchar(255) NOT NULL, PRIMARY KEY (`DELICACY_ID`));

CREATE TABLE DELICACY_INGREDIENT
(INGREDIENT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, INGREDIENT_NAME varchar(255) NOT NULL, DELICACY_ID INT UNSIGNED NOT NULL, DELICACY_MAT_ID INT UNSIGNED NOT NULL, INGREDIENT_UNIT varchar(255) NOT NULL, INGREDIENT_VOL DOUBLE NOT NULL, PRIMARY KEY (`INGREDIENT_ID`));

CREATE TABLE DELICACY_MATERIAL
(MATERIAL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, MATERIAL_NAME varchar(255) NOT NULL, MATERIAL_DES varchar(255) NOT NULL, MATERIAL_TYPE varchar(255) NOT NULL, PRIMARY KEY (`MATERIAL_ID`));

CREATE TABLE DELICACY_MEDIA
(MEDIA_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, MEDIA_NAME varchar(255) NOT NULL, MEDIA_URL varchar(255) NOT NULL, MEDIA_TYPE varchar(255) NOT NULL, PRIMARY KEY (`MEDIA_ID`));

CREATE TABLE DELICACY_OBJ_MED_REL
(RELATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, OBJ_ID INT UNSIGNED NOT NULL, MEDIA_ID INT UNSIGNED NOT NULL, DELICACY_OBJ_TYPE INT UNSIGNED NOT NULL, PRIMARY KEY (`RELATION_ID`));

CREATE TABLE DELICACY_STEP
(STEP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, STEP_NUM INT UNSIGNED NOT NULL, STEP_NAME varchar(255) NOT NULL, STEP_DESCRIPTION TEXT NOT NULL, STEP_TIME INT UNSIGNED NOT NULL, DELICACY_ID INT UNSIGNED NOT NULL, PRIMARY KEY (`STEP_ID`));

CREATE TABLE DELICACY_TAG
(TAG_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, TAG_NAME varchar(255) NOT NULL, TAG_COLOR INT UNSIGNED NOT NULL, PRIMARY KEY (`TAG_ID`))

CREATE TABLE DELICACY_TAG_RELATION
(RELATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, DELICACY_ID INT UNSIGNED NOT NULL, TAG_ID INT UNSIGNED NOT NULL, PRIMARY KEY (`RELATION_ID`))
