CREATE TABLE INSPIRATION
(INSPIRATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, INSPIRATION_TITLE varchar(255) NOT NULL, INSPIRATION_LOCATION varchar(255) NOT NULL, INSPIRATION_POSTTIME datetime NOT NULL, PRIMARY KEY (`INSPIRATION_ID`));

CREATE TABLE TAG
(TAG_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, TAG_NAME varchar(255) NOT NULL, TAG_COLOR INT UNSIGNED NOT NULL, PRIMARY KEY (`TAG_ID`));

CREATE TABLE INSPIRATION_M2M_TAG
(RELATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, INSPIRATION_ID INT UNSIGNED NOT NULL, TAG_ID INT UNSIGNED NOT NULL, PRIMARY KEY (`RELATION_ID`));
